# Generated by Django 5.1.6 on 2025-02-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_extractor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentdatareport',
            name='ai_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
