# Generated by Django 5.1.6 on 2025-02-19 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_extractor', '0002_alter_contentdatareport_ai_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentdatareport',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='contentdatareport',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ContentDataReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.FileField(upload_to='uploads/screenshots/')),
                ('screenshot_type', models.PositiveSmallIntegerField(choices=[(1, 'Full'), (2, 'Partial')])),
                ('content_data_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_data_report_images', to='image_extractor.contentdatareport')),
            ],
        ),
    ]
