# Generated by Django 5.1.6 on 2025-02-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_extractor', '0003_remove_contentdatareport_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdatareport',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to='uploads/recordings/'),
        ),
    ]
