# Generated by Django 5.1.6 on 2025-02-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_extractor', '0004_contentdatareport_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdatareport',
            name='ai_response_generation_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'IN_PROGRESS'), (1, 'SUCCESS')], default=0),
        ),
    ]
